[build]
  base = ""
  publish = "app/build/web"
  command = """
    git clone https://github.com/flutter/flutter.git -b stable --depth 1
    export PATH="$PATH:$(pwd)/flutter/bin"
    cd app
    flutter pub get
    flutter build web
  """